//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Torti
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oborudovanie
    {
        public string Label { get; set; }
        public string Type_oborudovanie { get; set; }
        public string Characteristics { get; set; }
    
        public virtual Type_oborudovanie Type_oborudovanie1 { get; set; }
    }
}
