//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Torti
{
    using System;
    using System.Collections.Generic;
    
    public partial class Specific_operation
    {
        public string Product { get; set; }
        public string Operation { get; set; }
        public int Poryadkovyy_nomer { get; set; }
        public string Oborudovanie_type { get; set; }
        public int Vremya_na_operatsiyu { get; set; }
    
        public virtual Izdelie Izdelie { get; set; }
        public virtual Type_oborudovanie Type_oborudovanie { get; set; }
    }
}
