//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Torti
{
    using System;
    using System.Collections.Generic;
    
    public partial class Specific_tort_decoration
    {
        public string Product { get; set; }
        public string Tort_decoration { get; set; }
        public int Amount { get; set; }
    
        public virtual Izdelie Izdelie { get; set; }
        public virtual Tort_decoration Tort_decoration1 { get; set; }
    }
}
