//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Torti
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tort_decoration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tort_decoration()
        {
            this.Specific_tort_decoration = new HashSet<Specific_tort_decoration>();
        }
    
        public string Arctikul { get; set; }
        public string Name { get; set; }
        public string Edinitsa_izmereniya { get; set; }
        public Nullable<int> Amount { get; set; }
        public string Main_postavshik { get; set; }
        public string Type { get; set; }
        public string Price { get; set; }
        public string Ves { get; set; }
    
        public virtual Postavshik Postavshik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Specific_tort_decoration> Specific_tort_decoration { get; set; }
    }
}
