//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Torti
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zakaz
    {
        public int Number { get; set; }
        public System.DateTime Date { get; set; }
        public string Name_zakaz { get; set; }
        public string Product { get; set; }
        public string Zakazchik { get; set; }
        public string Manager { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<System.DateTime> Plan_data_zaver { get; set; }
        public byte[] Primery_rabot { get; set; }
    
        public virtual Izdelie Izdelie { get; set; }
        public virtual Polzovatel Polzovatel { get; set; }
        public virtual Polzovatel Polzovatel1 { get; set; }
    }
}
